* Download the Iris dataset,  and normalise it.
* Run 1st algorithm and 2nd algorithm on it, with values of beta from 1.1 until 3.0 in steps of 0.1 (run 30 times each value of beta). 
* Calculate the adjusted rand index for each, show the average per beta for each algorithm.

In [11]:
from sklearn.datasets import load_iris

# Load the Iris dataset
iris = load_iris()

# Access the features (X) and target (y) data
X = iris.data
y = iris.target

# Optional: Print the description of the dataset
print(iris.DESCR)


.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [12]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [14]:
import numpy as np
np.max(X, axis = 0) - np.min(X, axis = 0)

array([3.6, 2.4, 5.9, 2.4])

In [15]:
n_clusters = 3
n_features = X.shape[1]
n_samples = X.shape[0]
print(f'Number of clusters :{n_clusters}')
print(f"Number of features:{n_features}")
print(f"Number of samples: {n_samples}")

Number of clusters :3
Number of features:4
Number of samples: 150


In [16]:
import numpy as np
def normalizer(data):
    return (data - np.mean(data,axis=0)) / (np.max(data, axis=0) - np.min(data, axis=0))

    

In [17]:
X_norm = normalizer(X)
X_norm

array([[-2.06481481e-01,  1.84444444e-01, -3.99661017e-01,
        -4.16388889e-01],
       [-2.62037037e-01, -2.38888889e-02, -3.99661017e-01,
        -4.16388889e-01],
       [-3.17592593e-01,  5.94444444e-02, -4.16610169e-01,
        -4.16388889e-01],
       [-3.45370370e-01,  1.77777778e-02, -3.82711864e-01,
        -4.16388889e-01],
       [-2.34259259e-01,  2.26111111e-01, -3.99661017e-01,
        -4.16388889e-01],
       [-1.23148148e-01,  3.51111111e-01, -3.48813559e-01,
        -3.33055556e-01],
       [-3.45370370e-01,  1.42777778e-01, -3.99661017e-01,
        -3.74722222e-01],
       [-2.34259259e-01,  1.42777778e-01, -3.82711864e-01,
        -4.16388889e-01],
       [-4.00925926e-01, -6.55555556e-02, -3.99661017e-01,
        -4.16388889e-01],
       [-2.62037037e-01,  1.77777778e-02, -3.82711864e-01,
        -4.58055556e-01],
       [-1.23148148e-01,  2.67777778e-01, -3.82711864e-01,
        -4.16388889e-01],
       [-2.89814815e-01,  1.42777778e-01, -3.65762712e-01,
      

In [18]:
np.max(X_norm, axis = 0) - np.min(X_norm, axis = 0)

array([1., 1., 1., 1.])

In [19]:
X.shape

(150, 4)

# First algorithm

In [20]:
from sklearn.metrics import adjusted_rand_score
from  WKmeans import wkmeans
from utils import clusters_vec

In [21]:


repetition = 5 # number of repetition for each beta
beta_values = np.arange(1.1, 1.5, 0.1).round(1).tolist()


average_adjusted_rand_score_array = np.zeros_like(beta_values)

for b, beta in enumerate(beta_values):
    adjusted_rand_score_array = np.zeros(repetition)
    for i in range(repetition):
        history = wkmeans(X_norm, n_clusters, beta)
        U = history["U"][-1]
        clusters = clusters_vec(U)
        a_r_s = adjusted_rand_score(y, clusters )
        adjusted_rand_score_array[i] = a_r_s

    average_adjusted_rand_score_array[b] =  adjusted_rand_score_array.mean()   
    





4.55066257889638
1.378672129111866
1.124363429689426
0.3333603298097412
0.7356746308582043
0.4344248030879678
0.06174199508411804
0.13637923916208017
0.07298457171112949
0.4604190156721295
0.20827095462781497
0.04527703618394541
0.35051848931518914
0.01418471171514879
0.002839504217317712
0.029127733018159185
0.0
0.08199154713149204
0.03146542169854549
0.3176385881246746
0.24689576711161831
0.3429772070761068
0.06572395226759187
0.1978257705368569
0.0
0.20958795409648712
2.23356479147992
2.8565597537803993
0.14142027571381588
0.11713242469555252
0.007401239451209296
0.23627232481465033
0.03984691180711297
0.003440926207266326
0.20958319064209263
0.01779942001142598
0.0019529169508527566
0.03146509013499754
0.010074191776124009
0.001101342709138864
0.03904586587123693
0.0
0.6609652984624508
0.45140930507856036
0.0006882343895919796
1.0126564983096389
0.5993918255182618
0.12065957294702989
1.7640135747123686
2.2460898989992275
0.2462315976672501
0.9411567964058273
0.43085706500662746
0.1

KeyboardInterrupt: 

In [ ]:
# with a beta of 1.1 for 1000 times, I should get a  number of mean Adjust RAND Index of about 0.6

In [7]:
history = wkmeans(X_norm, n_clusters,1.1 )
U = history["U"][-1]
clusters = clusters_vec(U)
a_r_s = adjusted_rand_score(y, clusters )
a_r_s

KeyError: 'z'

In [36]:
for i in range(repetition):
        history = wkmeans(X_norm, n_clusters, 1.1)
        U = history["U"][-1]
        clusters = clusters_vec(U)
        a_r_s = adjusted_rand_score(y, clusters )
        adjusted_rand_score_array[i] = a_r_s

adjusted_rand_score_array.mean()   

KeyboardInterrupt: 

In [ ]:
import matplotlib.pyplot as plt

# Plot the data
plt.plot(beta_values,average_adjusted_rand_score_array )

# Add labels and title
plt.xlabel('beta values')
plt.ylabel('Average of Adjusted Rand Score')
plt.title('First Algorithm ')

# Show the plot
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

# Second Algorithm

In [31]:
from sklearn.metrics import adjusted_rand_score
from  SubspaceWKmeans import sub_w_k_means
from utils import clusters_vec

repetition = 30 # number of repetition for each beta
beta_values = np.arange(1.1, 3.1, 0.1).round(1).tolist()


average_adjusted_rand_score_array = np.zeros_like(beta_values)

for b, beta in enumerate(beta_values):
    adjusted_rand_score_array = np.zeros(repetition)
    for i in range(repetition):
        history = sub_w_k_means(X_norm, n_clusters, beta)
        U = history["U"][-1]
        clusters = clusters_vec(U)
        a_r_s = adjusted_rand_score(clusters, y)
        adjusted_rand_score_array[i] = a_r_s

    average_adjusted_rand_score_array[b] =  adjusted_rand_score_array.mean()   
    


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:


# True labels
true_labels = [0, 0, 1, 1, 2, 2]

# Predicted labels
predicted_labels = [0, 0, 1, 1, 3, 3]

# Calculate ARI
ari = adjusted_rand_score(true_labels, predicted_labels)

print("Adjusted Rand Index:", ari)


Adjusted Rand Index: 1.0
