In [1]:
import numpy as np
import pandas as pd

In [2]:
# producing clustering dataset
from sklearn.datasets import make_blobs

n_samples = 200
n_features = 6
n_clusters = 4
# Generate random clustering dataset with 100 samples and 4 centers
X, y = make_blobs(n_samples=n_samples, n_features=n_features , centers=n_clusters, random_state=42)


df_x = pd.DataFrame(X)
df_y = pd.DataFrame(y)
df = pd.concat([df_x, df_y], axis=1)
df.columns = ['f0', 'f1','f2','f3','f4','f5','cluster']
df




f0        f1        f2        f3         f4         f5  cluster
0   -8.762523  6.646361  2.997420  4.014394 -10.413807   9.076811        1
1   -2.994561  9.096160  6.954537  0.105904  -6.193367  -8.492825        0
2   -3.355991  7.499439  4.193364  2.829568  -6.665533  -8.125848        0
3   -0.171629 -5.403025  2.834458 -6.508950  -4.454671  -1.297056        3
4   -9.077276  6.415959  1.445529  4.916843  -9.087393   8.420642        1
..        ...       ...       ...       ...        ...        ...      ...
195 -0.575299 -3.749960  1.270082 -7.257834  -4.160710  -3.831128        3
196  6.616100 -6.296643 -7.076346 -6.225480  -4.170132   1.999122        2
197 -1.962100  8.812093  4.422198  3.071947  -6.054211  -6.066600        0
198 -1.723541 -5.295087  0.942376 -6.049296  -4.624808  -2.326259        3
199 -7.779903  5.564783  0.839042  2.122219  -9.857717  10.115739        1

[200 rows x 7 columns]

## Initialization

In [3]:
# Dictionary of history
history = {
    'U': [],
    'Z': [],
    'W': [],
    'cost': []

    }
time_step = 0

In [4]:
# initial centers randomly by choosing from hte dataset randomly
Z_initial_index = np.random.choice(range(n_samples), size=n_clusters)
Z_initial_index

array([140, 178,  95, 160])

In [5]:
# Centers of clusters of random samples of data, but they can be any random data_points not necessarily in dataset
Z_df = df.iloc[Z_initial_index,:-1]
Z_df

f0        f1        f2        f3         f4         f5
140 -8.199735  5.662003  1.956220  2.950435 -10.240146   9.445596
178 -3.348415  8.705074  4.971142  2.948715  -7.358801  -7.065769
95  -8.471730  6.383643  1.508433  3.102238  -9.650989  10.353339
160 -9.108203  6.344759  1.578007  4.538752  -8.831321   8.476032

In [6]:
# Z_df to ndarray
Z = Z_df.to_numpy()
Z

array([[ -8.1997353 ,   5.66200285,   1.95622044,   2.95043536,
        -10.24014622,   9.44559571],
       [ -3.34841515,   8.70507375,   4.97114227,   2.94871481,
         -7.35880143,  -7.06576857],
       [ -8.47172951,   6.38364313,   1.50843332,   3.10223803,
         -9.65098921,  10.35333936],
       [ -9.10820269,   6.3447592 ,   1.57800697,   4.53875205,
         -8.8313215 ,   8.47603172]])

In [7]:
history['Z'].append(Z)

In [8]:
# Generate random weights that sum up to 1
weights = np.random.dirichlet(np.ones(n_features), size=1).squeeze()
weights


array([0.20792891, 0.09375181, 0.31333535, 0.03647016, 0.06505529,
       0.28345848])

In [9]:
weights.sum()

1.0

In [10]:
history['W'].append(weights)

In [11]:
history

{'U': [],
 'Z': [array([[ -8.1997353 ,   5.66200285,   1.95622044,   2.95043536,
          -10.24014622,   9.44559571],
         [ -3.34841515,   8.70507375,   4.97114227,   2.94871481,
           -7.35880143,  -7.06576857],
         [ -8.47172951,   6.38364313,   1.50843332,   3.10223803,
           -9.65098921,  10.35333936],
         [ -9.10820269,   6.3447592 ,   1.57800697,   4.53875205,
           -8.8313215 ,   8.47603172]])],
 'W': [array([0.20792891, 0.09375181, 0.31333535, 0.03647016, 0.06505529,
         0.28345848])],
 'cost': []}

• U is an M × k partition matrix, ui,l is a binary variable, and ui,l = 1 indicates that record i is allocated to cluster l.  
• Z = {Z1, Z2, ..., Zk} is a set of k vectors representing the k-cluster centers.  
• W = [w1, w2, ..., wN ] is a set of weights.  
• d(xi,j, zl,j) is a distance or dissimilarity measure between object i and the center of cluster l on the jth feature.

1. P1: Fix Z and W ; solve the reduced problem for U
2. P2: Fix U and W ; solve the reduced problem for Z
3. P3: Fix U and Z ; solve the reduced problem for W

In [12]:
def weighted_distance(s1, s2, weight_vec, beta):
    """Calculate the weighted distance between two samples s1 and  s2 and based on the weights that each feature has

    Args:
        s1 (ndarray): _description_
        s2 (ndarray): _description_
        weight_vec (ndarray): a vector of size (n_features, ), each element is the weight of corresponding feature.
        beta (scaler): the power of weights vector

    Returns:
        scaler: the weighted distance between two samples
    """
    distance_vec = np.square(s1 - s2) # Element_wise --> for each feature
    # w**beta
    weights_beta_vector = np.power(weight_vec, beta)

    weighted_distance = np.dot(distance_vec, weights_beta_vector.T)
    return weighted_distance

In [13]:
weighted_distance(Z[0],X[0], weights, 2)

0.1412066709406415

In [14]:
def closest_center(sample, centers, weight_vector, beta=2):
    """it takes a sample and compare its distance to centers of clusters and return the cluster with closest center.

    Args:
        sample (ndarray): A vector that represent a data point
        centers (ndarray): A ndarray with the shape of (n_clusters, n_features) where each row represent a center of a cluster
        weight_vector (ndarray): a vector of wights for corresponding feature
        beta (scaler): a bridge that bring
    Returns:
        int: the number of cluster which is closest to the samples
    """
    d = [] # list of weighted distances
    for c in centers:
        w_d = weighted_distance(sample, c, weight_vector, beta)
        d.append(w_d)
    assigned_cluster = np.argmin(d)
    return assigned_cluster

## Solving P1

In [15]:
def u_calculation(data, centers, weights, beta = 2):
   """ Calculate U based on Z and W and our dataset
   """
   n_spl = data.shape[0] # umber of samples
   n_clu = centers.shape[0] # number of clusters
   u_matrix = np.zeros((n_spl, n_clu))
   for i, x in enumerate(data):
      l = closest_center(x, centers, weights, beta)
      u_matrix[i][l] = 1
   return u_matrix

In [16]:
U = u_calculation(X, Z, weights)
U

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],


In [17]:
history['U'].append(U)

In [18]:
def clusters_vec(U):
    # a vector of size (n_samples, ) which each element shows the cluster that each samples is assigned to
    c_vec = np.zeros(n_samples)
    for m, u in enumerate(U):
        c_vec[m] = np.argmax(u)
    c_vec = c_vec.astype(int)
    return c_vec

In [19]:
clusters_vec(U)

array([0, 1, 1, 1, 3, 1, 3, 1, 1, 1, 2, 1, 1, 3, 3, 1, 1, 1, 1, 0, 1, 3,
       1, 2, 1, 1, 1, 0, 3, 3, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 3, 1, 1, 1,
       1, 1, 0, 1, 3, 1, 2, 1, 1, 3, 3, 0, 3, 2, 3, 1, 3, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 0, 1, 0, 3, 1, 1, 1, 3, 1,
       3, 1, 1, 3, 3, 1, 1, 2, 0, 1, 3, 1, 1, 1, 2, 3, 1, 1, 2, 1, 3, 3,
       1, 2, 1, 1, 1, 1, 1, 1, 3, 1, 0, 1, 3, 3, 1, 1, 1, 0, 1, 1, 3, 3,
       3, 1, 3, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 3, 0, 1, 1,
       0, 3, 1, 3, 3, 1, 3, 1, 1, 1, 1, 3, 0, 1, 1, 1, 1, 1, 3, 3, 1, 2,
       3, 3, 1, 1, 2, 1, 1, 0, 3, 3, 1, 1, 1, 3, 1, 1, 3, 3, 1, 1, 3, 1,
       1, 2])

In [20]:
unique_elements, counts = np.unique(clusters_vec(U), return_counts=True)
dict(zip(unique_elements, counts))

{0: 18, 1: 121, 2: 13, 3: 48}

In [21]:
def cost_function(U, Z, W, X, beta = 2):
    """Calculate the cost function

    Args:
        U (ndarray):  U is an (M, k) matrix, ui,l is a binary variable, and ui,l = 1 indicates that record i is allocated to cluster l.
        Z (ndarray): is a set of k vectors representing the k-cluster centers of size (n_clusters, n_features)
        W (ndarray): W = [w1, w2, ..., wN ] is a set of weights of size (n_features, )
        X (ndarray): matrix of records (n_records, n_features)
        beta (int, optional): The power of elements of weights vector Defaults to 2.
    """
    P = 0 # initial value of cost

    cl_vec = clusters_vec(U)
    
    # Updating P
    for m, c in enumerate(cl_vec):
        w_d = weighted_distance(X[m], Z[c], W, beta)
        P += w_d
        P =  P.item() # to convert it to a single scaler
    return(P)


In [22]:
c_t = cost_function(U, Z, weights, X, beta = 2)
history['cost'].append(c_t)

## Solving P2

In [23]:
def clusters_dict(U):
    # Finding the index of samples in each cluster
    n_clusters = U.shape[1]
    cluster_dict = {}
    clu_vec = clusters_vec(U)

    for i in range(n_clusters):
        cluster_dict[i] = np.where(clu_vec == i)[0]
        
    return cluster_dict

In [24]:
# Z_update = np.zeros_like(Z)
# for i,ind in cluster_dict.items():
#     Z_update[i] = np.mean(X[ind], axis=0)

# Z = Z_update


In [25]:
def update_Z(U, Z, X):
    """Update Z i.e. the centers of clusters, by taking mean of teh samples in each cluster
    """
    cluster_dict = clusters_dict(U)

    new_Z = np.zeros_like(Z)
    for i,ind in cluster_dict.items():
        new_Z[i] = np.mean(X[ind], axis=0)
    
    return new_Z


In [26]:
# Update Z
Z = history['Z'][-1] # the last update of Z
weights = history['W'][-1] # the last update of weights

Z_t = update_Z(U, Z, X) # new update of Z
history['Z'].append(Z_t)

In [27]:
# Update cost
c_t = cost_function(U, Z_t, weights, X, beta = 2) 
history['cost'].append(c_t)


In [28]:
history['cost']

[1357.123070684594, 633.2688388565273]

## Solving P3

In [29]:
# # Iteration over all features to calculate Dj
# U = history['U'][-1] # the lsat update of U
# Z = history['Z'][-1] # the lsat update of Z
# cluster_dict = clusters_dict(U)

# D = []
# for j in range(n_features):
#     d_j = 0
#     for l in range(n_clusters):
#         inx_in_cluster = cluster_dict[l]
#         # Distance for feature "j" in cluster "l"
#         d_j_l =np.sum(np.square(X[inx_in_cluster][j]-Z[l][j]))
#         d_j += d_j_l

#     D.append(d_j)

# D


In [30]:
def dj(X, U, Z):
    # Iteration over all features to calculate Dj for each feature
    
    cluster_dict = clusters_dict(U)
    n_features = X.shape[1]
    n_clusters = U.shape[1]
    
    D = []
    for j in range(n_features):
        d_j = 0
        for l in range(n_clusters):
            inx_in_cluster = cluster_dict[l]
            # Distance for feature "j" in cluster "l"
            d_j_l =np.sum(np.square(X[inx_in_cluster][j]-Z[l][j]))
            d_j += d_j_l

        D.append(d_j)
    return D


In [31]:
U = history['U'][-1] # the lsat update of U
Z = history['Z'][-1] # the lsat update of Z
d = dj(X, U, Z)
d

[2401.4304522138245,
 1619.4772747270167,
 1083.13095666796,
 1153.5709902598583,
 2743.526073273181,
 2356.3832383853282]

In [32]:
# # weights_update
# weights_update = np.zeros_like(weights)
# beta = 2

# # wherever D is zero, the corresponding weight is zero
# ind_D_zero = np.where(D == 0 )[0]
# weights_update[ind_D_zero] = 0

# ind_D_not_zero = np.where(D)[0]
# for j in ind_D_not_zero:
#     Dj_Dt = 0
    
#     for t in ind_D_not_zero:
#        Dj_Dt += (D[j] / D[t]) ** (1 / ( beta - 1) )
    
#     weights_update[j] = 1 / Dj_Dt

# weights_update

In [33]:
def weight_update(X, U, Z, weights, beta=2):

    # D calculation:
    D = dj(X, U, Z)

    
    # weights_update
    weights_upd = np.zeros_like(weights)


    # wherever D is zero, the corresponding weight is zero
    ind_D_zero = np.where(D == 0 )[0] # indexes of zero Dj
    weights_upd[ind_D_zero] = 0

    # D is not zero
    ind_D_not_zero = np.where(D)[0] ## indexes of non-zero Dj
    for j in ind_D_not_zero:
        
        Dj_Dt = 0
        for t in ind_D_not_zero:
            Dj_Dt += (D[j] / D[t]) ** (1 / ( beta - 1) )
        
        weights_upd[j] = 1 / Dj_Dt

    return weights_upd

In [34]:
# c_t = cost_function(U, Z, weights_update, X, beta = 2)
# c_t

In [35]:
U = history['U'][-1] # the lsat update of U
Z = history['Z'][-1] # the lsat update of Z
weights_t = weight_update(X, U, Z, weights, beta=2)
history['W'].append(weights_t)
c_t = cost_function(U, Z, weights_t, X, beta = 2)
history['cost'].append(c_t)

In [36]:
history['cost']

[1357.123070684594, 633.2688388565273, 701.9910928994457]

In [37]:
# do it in a loop 
# keep track of changes for weights 

## Put everything together


In [38]:
cost_difference = []

while True:
    cost_difference = np.abs(history['cost'][-1] - history['cost'][-2])
    if  cost_difference > 0.0001:

        # P1 --> update U
        Z = history['Z'][-1] # the last update of Z
        weights = history['W'][-1] # the last update of W
        U = u_calculation(X, Z, weights)
        history['U'].append(U)
        U = history['U'][-1]
        # update cost
        c_t = cost_function(U, Z, weights, X, beta = 2)
        history['cost'].append(c_t)
    else:
        break


    #P2 --> update Z
    cost_difference = np.abs(history['cost'][-1] - history['cost'][-2])
    if  cost_difference > 0.0001:
        U = history['U'][-1] # the last update of U
        Z = history['Z'][-1] # the last update of Z
        weights = history['W'][-1] # the last update of weights

        Z_t = update_Z(U, Z, X) # new update of Z
        history['Z'].append(Z_t)
        # Update cost
        c_t = cost_function(U, Z_t, weights, X, beta = 2) 
        history['cost'].append(c_t)
    else:
        break


    # P3 --> update  weights
    cost_difference = np.abs(history['cost'][-1] - history['cost'][-2])
    if  cost_difference > 0.0001:
        U = history['U'][-1] # the lsat update of U
        Z = history['Z'][-1] # the lsat update of Z
        weights_t = weight_update(X, U, Z, weights, beta=2)
        history['W'].append(weights_t)
        #update cost
        c_t = cost_function(U, Z, weights_t, X, beta = 2)
        history['cost'].append(c_t)
    else:
        break

final_weights = history['W'][-1]
print(f'Final vector of weights is:\n {final_weights} ')




Final vector of weights is:
 [0.1221552  0.14781306 0.1861069  0.24110764 0.14648307 0.15633414] 


In [39]:
history['cost']

[1357.123070684594,
 633.2688388565273,
 701.9910928994457,
 483.55057177647797,
 281.0950928260165,
 279.67408098944327,
 225.9105896624502,
 58.94471598521789,
 57.33138500827003,
 35.88445598240309,
 34.5107177182021,
 34.72282696450065,
 34.72282696450065]